victoire_core:
    widgets:
        LocaleSwitcher:
            class: "Victoire\\Widget\\LocaleSwitcherBundle\\Entity\\WidgetLocaleSwitcher"
            name: LocaleSwitcher
            cache: false
            
jms_translation:
    configs:
        victoire_localeswitcher_bundle:
            dirs: ["@VictoireLocaleSwitcherBundle"]
            output_dir: "@VictoireLocaleSwitcherBundle/Resources/translations"
